services:
  app:
    image: node:20-alpine3.19
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
      POSTGRES_HOST: db
    working_dir: /app
    tty: true
    entrypoint: "/bin/sh -c 'npm install; npm run typeorm migration:run -- -d src/app-data-source.ts; npm run start'"
    depends_on:
      - db

  db:
    image: postgres:16-alpine3.20
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - data:/var/lib/postgresql
    ports:
      - '5432:5432'

volumes:
  data:
