steps:
  - name: 'node:20-alpine3.19'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        echo "Installing dependencies..."
        mkdir -p /workspace/api
        cd /workspace/api
        cp /workspace/package*.json .
        npm install

  - name: 'node:20-alpine3.19'
    entrypoint: 'npm'
    args: ['run', 'build']
    dir: '/workspace/api'

  - name: 'node:20-alpine3.19'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        echo "Running migrations..."
        echo "DB_HOST: $_DB_HOST"
        echo "DB_USERNAME: $_DB_USERNAME"
        echo "DB_PASSWORD: $_DB_PASSWORD"
        echo "DB_DATABASE: $_DB_DATABASE"
        echo "DB_TYPEORM_ENTITIES: $_DB_TYPEORM_ENTITIES"
        echo "DB_TYPEORM_MIGRATIONS: $_DB_TYPEORM_MIGRATIONS"
        if npm run migrate; then
          echo "Migration completed successfully"
        else
          echo "Migration failed" >&2
          exit 1
        fi
    dir: '/workspace/api'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/hakobun/hakobun-api-image', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/hakobun/hakobun-api-image']

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'hakobun-api'
      - '--image=gcr.io/hakobun/hakobun-api-image'
      - '--platform=managed'
      - '--region=asia-northeast1'
      - '--allow-unauthenticated'

images:
  - 'gcr.io/hakobun/hakobun-api-image'
