name: Deploy to Cloud Run with Migration

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - '.github/workflows/backend_deploy.yaml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      ACTIONS_STEP_DEBUG: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCLOUD_AUTH }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          version: '>= 363.0.0'

      - name: Install dependencies
        run: npm install
        working-directory: ./backend

      - name: Build TypeScript
        run: npm run build
        working-directory: ./backend

        #あとで消す
      - name: Show current directory
        run: pwd

      - name: Show current directory
        run: pwd

      - name: List all files
        run: ls -R

      - name: List dist directory
        run: ls -l ./backend/dist

      - name: Run database migration
        run: npm run typeorm migration:run -- -d dist/app-data-source.js
        working-directory: ./backend
        env:
          _DB_HOST: ${{ secrets._DB_HOST }}
          _DB_USERNAME: ${{ secrets._DB_USERNAME }}
          _DB_PASSWORD: ${{ secrets._DB_PASSWORD }}
          _DB_DATABASE: ${{ secrets._DB_DATABASE }}
          _DB_TYPEORM_ENTITIES: ${{ secrets._DB_TYPEORM_ENTITIES }}
          _DB_TYPEORM_MIGRATIONS: ${{ secrets._DB_TYPEORM_MIGRATIONS }}

      # - name: Set up Cloud SQL Proxy
      #   run: |
      #     wget https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64 -O cloud_sql_proxy
      #     chmod +x cloud_sql_proxy
      #     ./cloud_sql_proxy -instances=${{ secrets.GCP_SQL_INSTANCE_CONNECTION }}=tcp:5432 &
      #     sleep 5

      # - name: Run database migration
      #   run: npm run typeorm migration:run -- -d src/app-data-source.ts
      #   working-directory: ./backend
      #   env:
      #     DB_HOST: 127.0.0.1
      #     DB_PORT: 5432
      #     DB_DATABASE: ${{ secrets.DB_NAME }}
      #     DB_USERNAME: ${{ secrets.DB_USER }}
      #     DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
